export const techList = [
  // Programming Languages
  { id: "c", name: "C", logo: "c" },
  { id: "cplusplus", name: "C++", logo: "cplusplus" },
  { id: "csharp", name: "C#", logo: "csharp" },
  { id: "go", name: "Go", logo: "go" },
  { id: "java", name: "Java", logo: "java" },
  { id: "javascript", name: "JavaScript", logo: "javascript" },
  { id: "typescript", name: "TypeScript", logo: "typescript" },
  { id: "php", name: "PHP", logo: "php" },
  { id: "perl", name: "Perl", logo: "perl" },
  { id: "ruby", name: "Ruby", logo: "ruby" },
  { id: "scala", name: "Scala", logo: "scala" },
  { id: "python", name: "Python", logo: "python" },
  { id: "swift", name: "Swift", logo: "swift" },
  { id: "objectivec", name: "Objective-C", logo: "apple" },
  { id: "clojure", name: "Clojure", logo: "clojure" },
  { id: "rust", name: "Rust", logo: "rust" },
  { id: "haskell", name: "Haskell", logo: "haskell" },
  { id: "coffeescript", name: "CoffeeScript", logo: "coffeescript" },
  { id: "elixir", name: "Elixir", logo: "elixir" },
  { id: "erlang", name: "Erlang", logo: "erlang" },
  { id: "nim", name: "Nim", logo: "nim" },

  // Frontend Development
  { id: "vuejs", name: "Vue.js", logo: "vuedotjs" },
  { id: "react", name: "React", logo: "react" },
  { id: "svelte", name: "Svelte", logo: "svelte" },
  { id: "angularjs", name: "AngularJS", logo: "angularjs" },
  { id: "angular", name: "Angular", logo: "angular" },
  { id: "backbonejs", name: "Backbone.js", logo: "backbone-dot-js" },
  { id: "bootstrap", name: "Bootstrap", logo: "bootstrap" },
  { id: "vuetify", name: "Vuetify", logo: "vuetify" },
  { id: "css3", name: "CSS3", logo: "css3" },
  { id: "html5", name: "HTML5", logo: "html5" },
  { id: "pug", name: "Pug", logo: "pug" },
  { id: "gulp", name: "Gulp", logo: "gulp" },
  { id: "sass", name: "Sass", logo: "sass" },
  { id: "redux", name: "Redux", logo: "redux" },
  { id: "webpack", name: "Webpack", logo: "webpack" },
  { id: "babel", name: "Babel", logo: "babel" },
  { id: "tailwind", name: "Tailwind CSS", logo: "tailwindcss" },
  { id: "materialize", name: "Materialize", logo: "materialdesign" },
  { id: "bulma", name: "Bulma", logo: "bulma" },
  { id: "gtk", name: "GTK", logo: "gtk" },
  { id: "qt", name: "Qt", logo: "qt" },
  { id: "wx_widgets", name: "wxWidgets", logo: "wxwidgets" },
  { id: "ember", name: "Ember.js", logo: "ember-dot-js" },

  // Backend Development
  { id: "nodejs", name: "Node.js", logo: "nodedotjs" },
  { id: "spring", name: "Spring", logo: "spring" },
  { id: "express", name: "Express.js", logo: "express" },
  { id: "graphql", name: "GraphQL", logo: "graphql" },
  { id: "kafka", name: "Kafka", logo: "apachekafka" },
  { id: "solr", name: "Apache Solr", logo: "apachesolr" },
  { id: "rabbitMQ", name: "RabbitMQ", logo: "rabbitmq" },
  { id: "hadoop", name: "Hadoop", logo: "apachehadoop" },
  { id: "nginx", name: "NGINX", logo: "nginx" },
  { id: "openresty", name: "OpenResty", logo: "openresty" },
  { id: "nestjs", name: "NestJS", logo: "nestjs" },

  // Mobile Development
  { id: "android", name: "Android", logo: "android" },
  { id: "flutter", name: "Flutter", logo: "flutter" },
  { id: "dart", name: "Dart", logo: "dart" },
  { id: "kotlin", name: "Kotlin", logo: "kotlin" },
  { id: "nativescript", name: "NativeScript", logo: "nativescript" },
  { id: "xamarin", name: "Xamarin", logo: "xamarin" },
  { id: "reactnative", name: "React Native", logo: "react" },
  { id: "ionic", name: "Ionic", logo: "ionic" },
  { id: "apachecordova", name: "Apache Cordova", logo: "apachecordova" },

  // AI / ML
  { id: "tensorflow", name: "TensorFlow", logo: "tensorflow" },
  { id: "pytorch", name: "PyTorch", logo: "pytorch" },
  { id: "pandas", name: "Pandas", logo: "pandas" },
  { id: "seaborn", name: "Seaborn", logo: "seaborn" },
  { id: "opencv", name: "OpenCV", logo: "opencv" },
  { id: "scikit_learn", name: "Scikit-learn", logo: "scikitlearn" },

  // Databases
  { id: "mongodb", name: "MongoDB", logo: "mongodb" },
  { id: "mysql", name: "MySQL", logo: "mysql" },
  { id: "postgresql", name: "PostgreSQL", logo: "postgresql" },
  { id: "redis", name: "Redis", logo: "redis" },
  { id: "oracle", name: "Oracle", logo: "oracle" },
  { id: "cassandra", name: "Cassandra", logo: "apachecassandra" },
  { id: "couchdb", name: "CouchDB", logo: "apachecouchdb" },
  { id: "hive", name: "Hive", logo: "apachehive" },
  { id: "realm", name: "Realm", logo: "realm" },
  { id: "mariadb", name: "MariaDB", logo: "mariadb" },
  { id: "cockroachdb", name: "CockroachDB", logo: "cockroachlabs" },
  { id: "elasticsearch", name: "Elasticsearch", logo: "elasticsearch" },
  { id: "sqlite", name: "SQLite", logo: "sqlite" },
  { id: "mssql", name: "MS SQL", logo: "microsoftsqlserver" },

  // Data Visualization
  { id: "d3js", name: "D3.js", logo: "d3-dot-js" },
  { id: "chartjs", name: "Chart.js", logo: "chartdotjs" },
  { id: "canvasjs", name: "CanvasJS", logo: "canvasjs" },
  { id: "kibana", name: "Kibana", logo: "kibana" },
  { id: "grafana", name: "Grafana", logo: "grafana" },

  // DevOps
  { id: "aws", name: "AWS", logo: "amazonwebservices" },
  { id: "docker", name: "Docker", logo: "docker" },
  { id: "jenkins", name: "Jenkins", logo: "jenkins" },
  { id: "gcp", name: "Google Cloud", logo: "googlecloud" },
  { id: "kubernetes", name: "Kubernetes", logo: "kubernetes" },
  { id: "bash", name: "Bash", logo: "gnubash" },
  { id: "azure", name: "Azure", logo: "microsoftazure" },
  { id: "vagrant", name: "Vagrant", logo: "vagrant" },
  { id: "circleci", name: "CircleCI", logo: "circleci" },
  { id: "travisci", name: "Travis CI", logo: "travisci" },

  // BaaS
  { id: "firebase", name: "Firebase", logo: "firebase" },
  { id: "appwrite", name: "Appwrite", logo: "appwrite" },
  { id: "amplify", name: "Amplify", logo: "awsamplify" },
  { id: "heroku", name: "Heroku", logo: "heroku" },

  // Frameworks
  { id: "django", name: "Django", logo: "django" },
  { id: "dotnet", name: ".NET", logo: "dotnet" },
  { id: "electron", name: "Electron", logo: "electron" },
  { id: "symfony", name: "Symfony", logo: "symfony" },
  { id: "laravel", name: "Laravel", logo: "laravel" },
  { id: "codeigniter", name: "CodeIgniter", logo: "codeigniter" },
  { id: "rails", name: "Ruby on Rails", logo: "rubyonrails" },
  { id: "flask", name: "Flask", logo: "flask" },
  { id: "quasar", name: "Quasar", logo: "quasar" },

  // Testing
  { id: "cypress", name: "Cypress", logo: "cypress" },
  { id: "selenium", name: "Selenium", logo: "selenium" },
  { id: "jest", name: "Jest", logo: "jest" },
  { id: "mocha", name: "Mocha", logo: "mocha" },
  { id: "puppeteer", name: "Puppeteer", logo: "puppeteer" },
  { id: "karma", name: "Karma", logo: "karma" },
  { id: "jasmine", name: "Jasmine", logo: "jasmine" },

  // Software Tools
  { id: "illustrator", name: "Adobe Illustrator", logo: "adobeillustrator" },
  { id: "photoshop", name: "Adobe Photoshop", logo: "adobephotoshop" },
  { id: "xd", name: "Adobe XD", logo: "adobexd" },
  { id: "figma", name: "Figma", logo: "figma" },
  { id: "blender", name: "Blender", logo: "blender" },
  { id: "sketch", name: "Sketch", logo: "sketch" },
  { id: "invision", name: "InVision", logo: "invision" },
  { id: "framer", name: "Framer", logo: "framer" },
  { id: "matlab", name: "MATLAB", logo: "matlab" },
  { id: "postman", name: "Postman", logo: "postman" },

  // Static Site Generators
  { id: "gatsby", name: "Gatsby", logo: "gatsby" },
  { id: "gridsome", name: "Gridsome", logo: "gridsome" },
  { id: "hugo", name: "Hugo", logo: "hugo" },
  { id: "jekyll", name: "Jekyll", logo: "jekyll" },
  { id: "nextjs", name: "Next.js", logo: "nextdotjs" },
  { id: "nuxtjs", name: "Nuxt.js", logo: "nuxtdotjs" },
  { id: "11ty", name: "Eleventy", logo: "eleventy" },
  { id: "scully", name: "Scully", logo: "scully" },
  { id: "sculpin", name: "Sculpin", logo: "sculpin" },
  { id: "sapper", name: "Sapper", logo: "sapper" },
  { id: "vuepress", name: "VuePress", logo: "vue-dot-js" },
  { id: "hexo", name: "Hexo", logo: "hexo" },
  { id: "middleman", name: "Middleman", logo: "middleman" },

  // Game Engines
  { id: "unity", name: "Unity", logo: "unity" },
  { id: "unreal", name: "Unreal Engine", logo: "unrealengine" },

  // Automation
  { id: "zapier", name: "Zapier", logo: "zapier" },
  { id: "ifttt", name: "IFTTT", logo: "ifttt" },

  // Other
  { id: "linux", name: "Linux", logo: "linux" },
  { id: "git", name: "Git", logo: "git" },
  { id: "arduino", name: "Arduino", logo: "arduino" },
];
